// Open Browser — main.cpp
// Entry point: initializes the GTK4 application and dispatches to BrowserWindow.

#include <gtk/gtk.h>
#include <webkit/webkit.h>
#include <glib.h>

#include <cstdlib>
#include <iostream>
#include <string>

#include "browser_window.h"
#include "settings_manager.h"
#include "bookmark_manager.h"
#include "history_manager.h"
#include "download_manager.h"

// Generated by CMake configure_file
#include "version.h"

namespace {

// Command line options storage
struct AppOptions {
    gboolean private_mode = FALSE;
    gboolean show_version = FALSE;
    gchar*   initial_url  = nullptr;
};

static AppOptions g_options;

static const GOptionEntry kOptionEntries[] = {
    {
        "private", 'p', G_OPTION_FLAG_NONE, G_OPTION_ARG_NONE,
        &g_options.private_mode,
        "Open in private browsing mode", nullptr
    },
    {
        "url", 'u', G_OPTION_FLAG_NONE, G_OPTION_ARG_STRING,
        &g_options.initial_url,
        "URL to open on launch", "URL"
    },
    {
        "version", 'v', G_OPTION_FLAG_NONE, G_OPTION_ARG_NONE,
        &g_options.show_version,
        "Print version and exit", nullptr
    },
    { nullptr, '\0', G_OPTION_FLAG_NONE, G_OPTION_ARG_NONE, nullptr, nullptr, nullptr }
};

// Called when the application is first activated (first instance).
static void on_activate(GApplication* app, gpointer /*user_data*/) {
    auto* gtk_app = GTK_APPLICATION(app);

    // Load persistent data stores
    open_browser::SettingsManager::instance().load();
    open_browser::BookmarkManager::instance().load();
    open_browser::HistoryManager::instance().load();

    const bool private_mode = static_cast<bool>(g_options.private_mode);
    auto* window = new open_browser::BrowserWindow(gtk_app, private_mode);

    const std::string url = g_options.initial_url
        ? std::string(g_options.initial_url)
        : open_browser::SettingsManager::instance().homepage();

    window->navigate(url);
    window->show();
}

// Called when the application receives a new 'open' command (e.g. clicking
// a link that targets this app while it is already running).
static void on_open(GApplication* app,
                    GFile**       files,
                    gint          n_files,
                    const gchar*  /*hint*/,
                    gpointer      /*user_data*/) {
    auto* gtk_app = GTK_APPLICATION(app);

    for (gint i = 0; i < n_files; ++i) {
        gchar* uri = g_file_get_uri(files[i]);
        if (uri) {
            // If a window already exists, open a new tab in it; otherwise
            // create a new window.
            GList* windows = gtk_application_get_windows(gtk_app);
            if (windows) {
                // Reuse the first (most-recently-focused) window.
                // We store the BrowserWindow pointer as window user data.
                auto* bw = static_cast<open_browser::BrowserWindow*>(
                    g_object_get_data(G_OBJECT(windows->data), "open-browser-window")
                );
                if (bw) {
                    bw->new_tab(uri);
                }
            } else {
                auto* window = new open_browser::BrowserWindow(gtk_app, false);
                window->navigate(uri);
                window->show();
            }
            g_free(uri);
        }
    }
}

// Called when command line options have been parsed.
static gint on_handle_local_options(GApplication* /*app*/,
                                    GVariantDict* /*options*/,
                                    gpointer       /*user_data*/) {
    if (g_options.show_version) {
        std::cout << "Open Browser " << OPEN_BROWSER_VERSION << "\n";
        std::cout << "WebKit " << webkit_get_major_version() << "."
                               << webkit_get_minor_version() << "."
                               << webkit_get_micro_version() << "\n";
        return 0; // Exit successfully without launching the app
    }
    return -1; // Continue normal startup
}

} // anonymous namespace

int main(int argc, char* argv[]) {
    // Enable hardware acceleration hint for Mesa/Wayland
    if (!g_getenv("WEBKIT_DISABLE_COMPOSITING_MODE")) {
        g_setenv("WEBKIT_DISABLE_COMPOSITING_MODE", "0", FALSE);
    }

    GtkApplication* app = gtk_application_new(
        OPEN_BROWSER_APP_ID,
        G_APPLICATION_HANDLES_OPEN
    );

    // Register command line options
    g_application_add_main_option_entries(G_APPLICATION(app), kOptionEntries);

    // Connect signals
    g_signal_connect(app, "activate",             G_CALLBACK(on_activate),             nullptr);
    g_signal_connect(app, "open",                 G_CALLBACK(on_open),                 nullptr);
    g_signal_connect(app, "handle-local-options", G_CALLBACK(on_handle_local_options), nullptr);

    const int status = g_application_run(G_APPLICATION(app), argc, argv);

    // Persist data before exit
    open_browser::BookmarkManager::instance().save();
    open_browser::HistoryManager::instance().save();
    open_browser::SettingsManager::instance().save();

    g_object_unref(app);
    return status;
}
